version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: web
    networks: 
      - shared-network
    ports: 
      - "8080:80"
    depends_on: 
      - db

  db:
    image: mysql:latest
    container_name: db
    networks: 
      - shared-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  kibana:
    image: kibana:6.4.2
    container_name: kibana
    networks: 
      - shared-network
    ports: 
      - "5601:5601"

volumes:
  db_data:
  
networks: 
  shared-network: {}